name: CI Backend & SonarQube Local

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths:
      - 'Backend/**'
      - 'pom.xml'
      - '.github/workflows/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'Backend/**'

jobs:
  build-and-analyze:
    name: Build & Analyze (Local)
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Install Common Lib
        run: |
          echo "Installing Common Lib..."
          cd Backend/common-lib  
          mvn clean install -DskipTests
          cd ../..                

      - name: SonarQube Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          JWT_SECRET: "secreto_super_seguro_para_testing_1234567890"
          POSTGRES_USER: "test"
          POSTGRES_PASSWORD: "test"
          EUREKA_CLIENT_ENABLED: "false"
          EUREKA_CLIENT_REGISTER_WITH_EUREKA: "false"
          EUREKA_CLIENT_FETCH_REGISTRY: "false"
        run: |
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=university-enrollment \
            -Dsonar.projectName='University Enrollment' \
            -Dsonar.qualitygate.wait=true